Fix enum values for hauler_type
DFHack/df-structures pull request #435
Opened 2021-08-22 21:45 UTC by myk002

While implementing the --hauler-type param for the prioritize script, I noticed that the `job->item_subtype` field, which is tagged as being a `hauler_type` enum, did not match up with the type of item being hauled. I fixed this enum based on observation of which enum values resulted in which types of items were hauled.

I was unabled to verify the "Bin" enum. I could not get any hauling jobs of this type to be generated in my fort, even when explicitly building bins and enabling bins for stockpiles.

2021-08-22 22:06 UTC, lethosor commented
This is an interesting one.

* The only place (supposedly) where hauler_type is used as a value is [here](https://github.com/DFHack/df-structures/blob/0.47.05-r2/df.jobs.xml#L109). This is used by labormanager [here](https://github.com/DFHack/dfhack/blob/0.47.05-r2/plugins/labormanager/joblabormapper.cpp#L254-L255) as a _`unit_labor`_, and your change would cause `unit_labor`s 1-8 to line up with `hauler_type`s 1-8. `Bin` (9 with your change) does not correspond to a HAUL_ unit_labor (where 9 = CLEAN).
* hauler_type is also used as an index-enum in `stockpile`, but @ab9rf reports that this enum was inaccurate at the time labormanager was written, so indices were hardcoded [here](https://github.com/DFHack/dfhack/blob/0.47.05-r2/plugins/labormanager/labormanager.cpp#L1673-L1692). Note that "bin" corresponded to 4 at the time.

My _guess_ is that Toady might have changed hauler_type at some point to be consistent with unit_labor, but I don't know for sure, or when.

2021-08-22 22:23 UTC, ab9rf requested changes
This would break the indexing of `world.stockpiles.num_jobs` and `world.stockpiles.num_haulers`. The current enum is correct; I tested this extensively over the course of years developing labormanager, and just spot-checked it in a mature fort.

> hauler_type is also used as an index-enum in stockpile, but @ab9rf reports that this enum was inaccurate at the time labormanager was written, so indices were hardcoded here. Note that "bin" corresponded to 4 at the time.

No, the enum is correct. I originally thought it was wrong, but it was more because I didn't understand how it was being used. There is no direct correspondence between hauling type and labors.

2021-08-22 22:23 UTC, ab9rf commented on df.stockpile.xml
>          <enum-item name='Food'/>
This is wrong, at least with respect to `world.stockpiles.num_haulers`, and I must recommend against this PR without more evidence.

I just tested on a mature forts by clearing all hauling labors on everyone. This resulted in `world.stockpiles.num_haulers` going to all zero. Then, reenabling food hauling on everyone resulted in `world.stockpiles.num_haulers[Food]` going to 194 while the others remained zero.

If the enum were wrong, some other field would have gone up. Therefore, the existing enum is correct, at least for food, but this change would change the value of the `Food` enum.

I must therefore object.

2021-08-22 22:45 UTC, lethosor commented
Thinking over it a bit, I suspect the [comment for `job.item_subtype`](https://github.com/DFHack/df-structures/blob/0.47.05-r2/df.jobs.xml#L109) is wrong, and this field is actually a `unit_labor` when `type == StoreItemInStockpile`. I'm not sure yet what implications this would have for https://github.com/DFHack/scripts/pull/327, though.

2021-08-23 00:21 UTC, myk002 commented
ack. I'll fix the comment and update DFHack/scripts#327 to interpret the field as a `unit_labor`. Thanks!

2021-08-23 00:25 UTC, myk002 commented
changes reverted; misleading comment made less misleading

2021-08-23 00:32 UTC, ab9rf commented
My research suggests that we should rename `Bin` to something else. Specifically, `StoreItemInHospital` jobs increment `world.stockpile.num_jobs[Bin]`, even though a "store in hospital" job never result in anything being actually stored in a bin.

```
        pjVar38 = job::create();
        piVar42 = local_440;
        pjVar38->job_type = StoreItemInHospital;
...
        world.stockpile.num_jobs.Any = world.stockpile.num_jobs.Any + 1;
        world.stockpile.num_jobs.Bin = world.stockpile.num_jobs.Bin + 1;
```

2021-08-23 10:40 UTC, ab9rf approved these changes

2021-08-24 16:24 UTC, merged