Updated tiletypes from Toady-supplied names
DFHack/df-structures pull request #550
Opened 2023-02-06 09:20 UTC by RosaryMala

2023-02-06 22:08 UTC, ab9rf approved these changes
as far as i can tell this only changes the names of a few that had `unk` in them which means nobody should have been using them

also, i assume the two blank values at the end are intentional

2023-02-06 22:10 UTC, RosaryMala commented
The two blank values at the end are part of the enum that Toady sent me that are unused. I should probably remove them.

2023-02-06 22:16 UTC, ab9rf requested changes
changelog plz

2023-02-06 22:21 UTC, ab9rf commented
> 



> The two blank values at the end are part of the enum that Toady sent me that are unused. I should probably remove them.

if they're in toady's enum then we should leave them in, although giving them a name (such as `UNUSED_nnn`) is a good idea

2023-02-07 01:13 UTC, ab9rf commented on df.tile-types.xml
> -        <enum-item/>
as i said previously, if those are actually on toady's provided list, they should also be included here with an appropriate name

2023-02-07 01:42 UTC, RosaryMala commented on changelog.txt
>  ## Structures
Done.

2023-02-07 02:33 UTC, myk002 approved these changes

2023-02-07 02:33 UTC, merged