update graphics with sdl2 changes
DFHack/df-structures pull request #605
Opened 2023-05-24 17:52 UTC by myk002

the `std::variant` representation may not be the best

2023-05-24 18:22 UTC, cvuchener commented
Where is the std::variant?

2023-05-24 18:26 UTC, myk002 commented
in g_src: https://github.com/Putnam3145/Dwarf-Fortress--libgraphics--/blob/sdl2/g_src/graphics.h#L2985

2023-05-26 23:59 UTC, ab9rf requested changes

2023-05-26 23:59 UTC, ab9rf commented on df.graphics.xml
> +        <uint8_t name='tex_n'/>
tag comes before the variant representation, not after

2023-05-27 01:13 UTC, ab9rf commented on df.graphics.xml
> +        <uint8_t name='tex_n'/>
nevermind, i'm wrong, this is correct except that the tag should be `int8_t` as `-1` is always a valid value for the union tag field

2023-05-27 01:36 UTC, ab9rf approved these changes

2023-05-27 01:36 UTC, merged